"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-24

Creates all tables defined in app.models plus the three reporting views.
Order respects FK dependencies. Migration is intentionally hand-written
rather than autogenerated so the SQL is reviewable end-to-end.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import ARRAY, CITEXT, JSONB, UUID

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Extensions required by the schema.
    #
    # OPERATIONAL NOTE: CREATE EXTENSION on Cloud SQL requires the
    # `cloudsqlsuperuser` role. The smfo-svc-runtime service account is a
    # regular application user — running this migration as that user fails
    # with "permission denied to create extension". Bootstrap path:
    #
    #   1. Connect to Cloud SQL as the `postgres` superuser (gcloud sql connect
    #      gabriel-agent-db --user=postgres).
    #   2. Run: CREATE EXTENSION IF NOT EXISTS pgcrypto;
    #           CREATE EXTENSION IF NOT EXISTS citext;
    #   3. THEN run `alembic upgrade head` as the smfo-svc-runtime user.
    #
    # IF NOT EXISTS makes the statements below safe to re-run if a future
    # extension is added and step 1-2 has already created the existing ones.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")  # gen_random_uuid
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")

    # --- family_branches ---
    op.create_table(
        "family_branches",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("slug", sa.String(64), nullable=False, unique=True),
        sa.Column("display_name", sa.String(128), nullable=False),
    )

    # --- principals (forward-ref FKs to other tables are added later) ---
    op.create_table(
        "principals",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("full_name", sa.String(128), nullable=False),
        sa.Column("surname_at_birth", sa.String(128), nullable=True),
        sa.Column("email_primary", CITEXT(), unique=True, nullable=True),
        sa.Column("role", sa.String(32), nullable=False),
        sa.Column("branch_id", UUID(as_uuid=True), sa.ForeignKey("family_branches.id"), nullable=True),
        sa.Column("is_approver", sa.Boolean, nullable=False, server_default=sa.text("false")),
        sa.Column("notes", sa.Text, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=True),
        sa.Column("updated_by", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=True),
    )

    # --- vehicle_types ---
    op.create_table(
        "vehicle_types",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("slug", sa.String(64), nullable=False, unique=True),
        sa.Column("display_name", sa.String(128), nullable=False),
    )

    # --- vehicles ---
    op.create_table(
        "vehicles",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("legal_name", sa.String(256), nullable=False),
        sa.Column("short_name", sa.String(64), nullable=False),
        sa.Column("vehicle_type_id", UUID(as_uuid=True), sa.ForeignKey("vehicle_types.id"), nullable=True),
        sa.Column("tax_id", sa.String(64), nullable=True),
        sa.Column("jurisdiction", sa.String(32), nullable=True),
        sa.Column("formed_on", sa.Date, nullable=True),
        sa.Column("closed_on", sa.Date, nullable=True),
        sa.Column("drive_folder_id", sa.String(128), nullable=True),
        sa.Column("notes", sa.Text, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=True),
        sa.Column("updated_by", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=True),
    )

    # --- vehicle_ownerships ---
    op.create_table(
        "vehicle_ownerships",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("vehicle_id", UUID(as_uuid=True), sa.ForeignKey("vehicles.id", ondelete="CASCADE"), nullable=False),
        sa.Column("principal_id", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=False),
        sa.Column("role", sa.String(32), nullable=False),
        sa.Column("ownership_pct", sa.Numeric(7, 4), nullable=True),
        sa.Column("effective_from", sa.Date, nullable=False),
        sa.Column("effective_to", sa.Date, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=True),
        sa.Column("updated_by", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=True),
        sa.UniqueConstraint(
            "vehicle_id", "principal_id", "role", "effective_from", name="uq_vehicle_ownerships"
        ),
    )

    # --- asset_classes ---
    op.create_table(
        "asset_classes",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("slug", sa.String(64), nullable=False, unique=True),
        sa.Column("display_name", sa.String(128), nullable=False),
        sa.Column("sort_order", sa.Integer, nullable=False, server_default="0"),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.text("true")),
    )

    # --- asset_sub_categories ---
    op.create_table(
        "asset_sub_categories",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("asset_class_id", UUID(as_uuid=True), sa.ForeignKey("asset_classes.id", ondelete="RESTRICT"), nullable=False),
        sa.Column("slug", sa.String(64), nullable=False),
        sa.Column("display_name", sa.String(128), nullable=False),
        sa.Column("sort_order", sa.Integer, nullable=False, server_default="0"),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.text("true")),
        sa.UniqueConstraint("asset_class_id", "slug", name="uq_asset_sub_categories"),
    )

    # --- taxonomy_audit ---
    op.create_table(
        "taxonomy_audit",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("entity_type", sa.String(32), nullable=False),
        sa.Column("entity_id", UUID(as_uuid=True), nullable=False),
        sa.Column("action", sa.String(32), nullable=False),
        sa.Column("previous_value", JSONB, nullable=True),
        sa.Column("new_value", JSONB, nullable=True),
        sa.Column("reason", sa.Text, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=True),
        sa.Column("updated_by", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=True),
    )

    # --- documents (created before investments to satisfy investments.card_document_id FK) ---
    op.create_table(
        "documents",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("drive_file_id", sa.String(128), unique=True, nullable=True),
        sa.Column("drive_parent_id", sa.String(128), nullable=True),
        sa.Column("filename", sa.String(512), nullable=False),
        sa.Column("mime_type", sa.String(128), nullable=True),
        sa.Column("sha256", sa.String(64), nullable=True, index=True),
        sa.Column("language", sa.String(8), nullable=True),
        sa.Column("source", sa.String(32), nullable=False),
        # source_email_id FK added later (email_messages doesn't exist yet)
        sa.Column("source_email_id", UUID(as_uuid=True), nullable=True),
        sa.Column("doc_type", sa.String(64), nullable=True),
        sa.Column("page_count", sa.Integer, nullable=True),
        sa.Column("normalized_md", sa.Text, nullable=True),
        sa.Column("extracted_json", JSONB, nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("status", sa.String(16), nullable=False, server_default="new"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=True),
        sa.Column("updated_by", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=True),
    )

    # --- investments ---
    op.create_table(
        "investments",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("name", sa.String(256), nullable=False),
        sa.Column("issuer", sa.String(256), nullable=True),
        sa.Column("asset_class_id", UUID(as_uuid=True), sa.ForeignKey("asset_classes.id"), nullable=False),
        sa.Column("sub_category_id", UUID(as_uuid=True), sa.ForeignKey("asset_sub_categories.id"), nullable=True),
        sa.Column("currency", sa.String(3), nullable=False, server_default="USD"),
        sa.Column("status", sa.String(16), nullable=False, server_default="active"),
        sa.Column("liquidity_type", sa.String(16), nullable=False, server_default="liquid"),
        sa.Column("lockup_until", sa.Date, nullable=True),
        sa.Column("card_document_id", UUID(as_uuid=True), sa.ForeignKey("documents.id"), nullable=True),
        sa.Column("notes", sa.Text, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=True),
        sa.Column("updated_by", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=True),
    )

    # --- investment_positions ---
    op.create_table(
        "investment_positions",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("investment_id", UUID(as_uuid=True), sa.ForeignKey("investments.id", ondelete="CASCADE"), nullable=False),
        sa.Column("vehicle_id", UUID(as_uuid=True), sa.ForeignKey("vehicles.id", ondelete="RESTRICT"), nullable=False),
        sa.Column("structure", sa.String(32), nullable=False),
        sa.Column("commitment_amount", sa.Numeric(20, 2), nullable=True),
        sa.Column("funded_amount", sa.Numeric(20, 2), nullable=True),
        sa.Column("current_value", sa.Numeric(20, 2), nullable=True),
        sa.Column("ownership_pct", sa.Numeric(9, 6), nullable=True),
        sa.Column("effective_from", sa.Date, nullable=False),
        sa.Column("effective_to", sa.Date, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=True),
        sa.Column("updated_by", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=True),
        sa.UniqueConstraint(
            "investment_id", "vehicle_id", "effective_from", name="uq_investment_positions"
        ),
    )

    # --- investment_cash_flows ---
    op.create_table(
        "investment_cash_flows",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("investment_id", UUID(as_uuid=True), sa.ForeignKey("investments.id", ondelete="RESTRICT"), nullable=False),
        sa.Column("vehicle_id", UUID(as_uuid=True), sa.ForeignKey("vehicles.id"), nullable=False),
        sa.Column("kind", sa.String(32), nullable=False),
        sa.Column("amount", sa.Numeric(20, 2), nullable=False),
        sa.Column("currency", sa.String(3), nullable=False, server_default="USD"),
        sa.Column("transaction_date", sa.Date, nullable=False),
        sa.Column("value_date", sa.Date, nullable=True),
        sa.Column("source_document_id", UUID(as_uuid=True), sa.ForeignKey("documents.id"), nullable=True),
        sa.Column("notes", sa.Text, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=True),
        sa.Column("updated_by", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=True),
    )

    # --- email_accounts ---
    op.create_table(
        "email_accounts",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("principal_id", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=False),
        sa.Column("email_address", CITEXT(), unique=True, nullable=False),
        sa.Column("account_type", sa.String(16), nullable=False, server_default="primary"),
        sa.Column("provider", sa.String(16), nullable=False, server_default="gmail"),
        sa.Column("oauth_subject", sa.String(128), nullable=False),
        sa.Column("last_history_id", sa.String(64), nullable=True),
        sa.Column("enabled", sa.Boolean, nullable=False, server_default=sa.text("true")),
        sa.Column("notes", sa.Text, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=True),
        sa.Column("updated_by", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=True),
    )

    # --- email_senders ---
    op.create_table(
        "email_senders",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("address", CITEXT(), unique=True, nullable=True),
        sa.Column("domain", sa.String(256), nullable=False, index=True),
        sa.Column("display_name", sa.String(256), nullable=True),
        sa.Column("status", sa.String(16), nullable=False),
        sa.Column("category", sa.String(32), nullable=True),
        sa.Column("default_investment_id", UUID(as_uuid=True), sa.ForeignKey("investments.id"), nullable=True),
        sa.Column("default_vehicle_id", UUID(as_uuid=True), sa.ForeignKey("vehicles.id"), nullable=True),
        sa.Column("approved_by", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("seed_source", sa.String(64), nullable=True),
        sa.Column("notes", sa.Text, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=True),
        sa.Column("updated_by", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=True),
    )

    # --- email_subject_patterns ---
    op.create_table(
        "email_subject_patterns",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("pattern", sa.String(512), nullable=False),
        sa.Column("pattern_type", sa.String(16), nullable=False, server_default="substring"),
        sa.Column("intent", sa.String(64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=True),
        sa.Column("updated_by", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=True),
    )

    # --- email_threads ---
    op.create_table(
        "email_threads",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("gmail_thread_id", sa.String(64), nullable=False),
        sa.Column("account_id", UUID(as_uuid=True), sa.ForeignKey("email_accounts.id"), nullable=False),
        sa.Column("subject", sa.String(1024), nullable=True),
        sa.Column("conversation_key", sa.String(128), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("investment_id", UUID(as_uuid=True), sa.ForeignKey("investments.id"), nullable=True),
        sa.Column("vehicle_id", UUID(as_uuid=True), sa.ForeignKey("vehicles.id"), nullable=True),
        sa.Column("status", sa.String(16), nullable=False, server_default="active"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=True),
        sa.Column("updated_by", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=True),
        sa.UniqueConstraint("gmail_thread_id", "account_id", name="uq_email_threads_per_account"),
    )
    op.create_index(
        "email_threads_conversation_key_idx", "email_threads", ["conversation_key"]
    )

    # --- email_messages ---
    op.create_table(
        "email_messages",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("thread_id", UUID(as_uuid=True), sa.ForeignKey("email_threads.id", ondelete="CASCADE"), nullable=False),
        sa.Column("gmail_message_id", sa.String(64), nullable=False),
        sa.Column("account_id", UUID(as_uuid=True), sa.ForeignKey("email_accounts.id"), nullable=False),
        sa.Column("direction", sa.String(16), nullable=False),
        sa.Column("from_address", CITEXT(), nullable=False),
        sa.Column("to_addresses", ARRAY(CITEXT()), nullable=False),
        sa.Column("cc_addresses", ARRAY(CITEXT()), nullable=False, server_default=sa.text("'{}'::citext[]")),
        sa.Column("subject", sa.String(1024), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("snippet", sa.Text, nullable=True),
        sa.Column("body_text", sa.Text, nullable=True),
        sa.Column("body_html", sa.Text, nullable=True),
        sa.Column("has_attachments", sa.Boolean, nullable=False, server_default=sa.text("false")),
        sa.Column("ingest_status", sa.String(16), nullable=False, server_default="pending"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=True),
        sa.Column("updated_by", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=True),
        sa.UniqueConstraint("gmail_message_id", "account_id", name="uq_email_messages_per_account"),
    )

    # Add the deferred FK from documents.source_email_id → email_messages.id now that the target exists.
    op.create_foreign_key(
        "fk_documents_source_email",
        "documents",
        "email_messages",
        ["source_email_id"],
        ["id"],
    )

    # --- investment_obligations (depends on email_messages, documents, principals) ---
    op.create_table(
        "investment_obligations",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("investment_id", UUID(as_uuid=True), sa.ForeignKey("investments.id", ondelete="CASCADE"), nullable=False),
        sa.Column("vehicle_id", UUID(as_uuid=True), sa.ForeignKey("vehicles.id"), nullable=True),
        sa.Column("kind", sa.String(32), nullable=False),
        sa.Column("due_on", sa.Date, nullable=True),
        sa.Column("amount", sa.Numeric(20, 2), nullable=True),
        sa.Column("currency", sa.String(3), nullable=False, server_default="USD"),
        sa.Column("description", sa.Text, nullable=True),
        sa.Column("status", sa.String(16), nullable=False, server_default="open"),
        sa.Column("source_kind", sa.String(16), nullable=False),
        sa.Column("source_document_id", UUID(as_uuid=True), sa.ForeignKey("documents.id"), nullable=True),
        sa.Column("source_email_message_id", UUID(as_uuid=True), sa.ForeignKey("email_messages.id"), nullable=True),
        sa.Column("source_slack_ts", sa.String(64), nullable=True),
        sa.Column("source_slack_channel", sa.String(64), nullable=True),
        sa.Column("source_principal_id", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=True),
        sa.Column("satisfied_at", sa.Date, nullable=True),
        sa.Column("satisfied_cash_flow_id", UUID(as_uuid=True), sa.ForeignKey("investment_cash_flows.id"), nullable=True),
        sa.Column("satisfied_by_principal", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=True),
        sa.Column("updated_by", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=True),
        sa.CheckConstraint(
            "source_kind = 'manual' OR "
            "source_document_id IS NOT NULL OR "
            "source_email_message_id IS NOT NULL OR "
            "(source_slack_ts IS NOT NULL AND source_slack_channel IS NOT NULL)",
            name="ck_investment_obligations_source",
        ),
    )
    op.create_index(
        "investment_obligations_open_idx",
        "investment_obligations",
        ["due_on"],
        postgresql_where=sa.text("status = 'open'"),
    )

    # --- document_links ---
    op.create_table(
        "document_links",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("document_id", UUID(as_uuid=True), sa.ForeignKey("documents.id", ondelete="CASCADE"), nullable=False),
        sa.Column("investment_id", UUID(as_uuid=True), sa.ForeignKey("investments.id"), nullable=True),
        sa.Column("vehicle_id", UUID(as_uuid=True), sa.ForeignKey("vehicles.id"), nullable=True),
        sa.Column("principal_id", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=True),
        sa.Column("link_role", sa.String(32), nullable=True),
        sa.Column("confidence", sa.Numeric(4, 3), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=True),
        sa.Column("updated_by", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=True),
        sa.CheckConstraint(
            "investment_id IS NOT NULL OR vehicle_id IS NOT NULL OR principal_id IS NOT NULL",
            name="ck_document_links_target",
        ),
    )

    # --- hdl_reviews ---
    op.create_table(
        "hdl_reviews",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("kind", sa.String(64), nullable=False),
        sa.Column("subject_table", sa.String(64), nullable=False),
        sa.Column("subject_id", UUID(as_uuid=True), nullable=False),
        sa.Column("proposed", JSONB, nullable=False),
        sa.Column("context", JSONB, nullable=False),
        sa.Column("status", sa.String(16), nullable=False, server_default="pending"),
        sa.Column("approved_by", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution", JSONB, nullable=True),
        sa.Column("channel", sa.String(16), nullable=False),
        sa.Column("slack_message_ts", sa.String(64), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    op.create_index(
        "hdl_reviews_pending_idx",
        "hdl_reviews",
        ["status"],
        postgresql_where=sa.text("status = 'pending'"),
    )

    # --- workflow_runs ---
    op.create_table(
        "workflow_runs",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("workflow", sa.String(64), nullable=False),
        sa.Column("subject_id", UUID(as_uuid=True), nullable=False),
        sa.Column("state", JSONB, nullable=False),
        sa.Column("status", sa.String(16), nullable=False),
        sa.Column("parent_run_id", UUID(as_uuid=True), sa.ForeignKey("workflow_runs.id"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )

    # --- audit_log ---
    op.create_table(
        "audit_log",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("occurred_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("actor_id", UUID(as_uuid=True), sa.ForeignKey("principals.id"), nullable=True),
        sa.Column("actor_kind", sa.String(16), nullable=False),
        sa.Column("action", sa.String(32), nullable=False),
        sa.Column("table_name", sa.String(64), nullable=False),
        sa.Column("row_id", UUID(as_uuid=True), nullable=False),
        sa.Column("diff", JSONB, nullable=True),
    )

    # --- Reporting views ---
    op.execute(
        """
        CREATE VIEW v_smfo_aggregate AS
        SELECT
          i.asset_class_id,
          ac.display_name AS asset_class,
          i.liquidity_type,
          i.sub_category_id,
          asc2.display_name AS sub_category,
          SUM(ip.current_value)     AS total_value,
          SUM(ip.commitment_amount) AS total_commitment,
          SUM(ip.funded_amount)     AS total_funded,
          COUNT(DISTINCT i.id)      AS investment_count
        FROM investment_positions ip
        JOIN investments i  ON i.id = ip.investment_id
        JOIN asset_classes ac ON ac.id = i.asset_class_id
        LEFT JOIN asset_sub_categories asc2 ON asc2.id = i.sub_category_id
        WHERE ip.effective_to IS NULL AND i.status = 'active'
        GROUP BY i.asset_class_id, ac.display_name, i.liquidity_type, i.sub_category_id, asc2.display_name;
        """
    )

    op.execute(
        """
        CREATE VIEW v_per_vehicle AS
        SELECT
          v.id           AS vehicle_id,
          v.short_name   AS vehicle,
          i.id           AS investment_id,
          i.name         AS investment,
          ac.display_name AS asset_class,
          i.liquidity_type,
          ip.commitment_amount, ip.funded_amount, ip.current_value,
          ip.ownership_pct, ip.structure
        FROM vehicles v
        JOIN investment_positions ip ON ip.vehicle_id = v.id
        JOIN investments i ON i.id = ip.investment_id
        JOIN asset_classes ac ON ac.id = i.asset_class_id
        WHERE ip.effective_to IS NULL;
        """
    )

    op.execute(
        """
        CREATE VIEW v_per_family AS
        SELECT
          fb.slug         AS branch,
          ac.display_name AS asset_class,
          SUM(ip.current_value * COALESCE(vo.ownership_pct, 100) / 100.0)     AS attributed_value,
          SUM(ip.commitment_amount * COALESCE(vo.ownership_pct, 100) / 100.0) AS attributed_commitment
        FROM family_branches fb
        JOIN principals p ON p.branch_id = fb.id AND p.is_approver = true
        JOIN vehicle_ownerships vo ON vo.principal_id = p.id AND vo.effective_to IS NULL
        JOIN vehicles v ON v.id = vo.vehicle_id
        JOIN investment_positions ip ON ip.vehicle_id = v.id AND ip.effective_to IS NULL
        JOIN investments i ON i.id = ip.investment_id
        JOIN asset_classes ac ON ac.id = i.asset_class_id
        WHERE i.status = 'active'
        GROUP BY fb.slug, ac.display_name;
        """
    )


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS v_per_family")
    op.execute("DROP VIEW IF EXISTS v_per_vehicle")
    op.execute("DROP VIEW IF EXISTS v_smfo_aggregate")
    op.drop_table("audit_log")
    op.drop_table("workflow_runs")
    op.drop_index("hdl_reviews_pending_idx", table_name="hdl_reviews")
    op.drop_table("hdl_reviews")
    op.drop_table("document_links")
    op.drop_index("investment_obligations_open_idx", table_name="investment_obligations")
    op.drop_table("investment_obligations")
    op.drop_constraint("fk_documents_source_email", "documents", type_="foreignkey")
    op.drop_table("email_messages")
    op.drop_index("email_threads_conversation_key_idx", table_name="email_threads")
    op.drop_table("email_threads")
    op.drop_table("email_subject_patterns")
    op.drop_table("email_senders")
    op.drop_table("email_accounts")
    op.drop_table("investment_cash_flows")
    op.drop_table("investment_positions")
    op.drop_table("investments")
    op.drop_table("documents")
    op.drop_table("taxonomy_audit")
    op.drop_table("asset_sub_categories")
    op.drop_table("asset_classes")
    op.drop_table("vehicle_ownerships")
    op.drop_table("vehicles")
    op.drop_table("vehicle_types")
    op.drop_table("principals")
    op.drop_table("family_branches")
